---

user:
  name: aereal
  group: staff

homebrew_cask:
  casks:
    - name: dropbox
    - name: alfred
    - name: iterm2
    - name: karabiner
    - name: slack
    - name: slate
    - name: limechat
    - name: virtualbox

homebrew_packages:
  packages:
    - name: openssl
    - name: coreutils
    - name: direnv
    - name: proctools
    - name: tmux
    - name: the_silver_searcher
    - name: pstree
    - name: proxychains-ng
    -
      name: reattach-to-user-namespace
      install_options:
        - with-wrap-launchctl
        - with-wrap-pbcopy-and-pbpaste
    -
      name: macvim
      install_options:
        - with-lua
        - with-luajit
        - override-system-vim

mackerel_agent:
  root: /usr/local/var/mackerel-agent
  pidfile: /usr/local/var/mackerel-agent/pid
  plugins:
    -
      formula:
        name: mackerel-agent-osx-plugins
      metric_name: macbook-battery
      command: ruby /usr/local/bin/mackerel-plugin-osx-battery

karabiner:
  config:
    repeat.initial_wait: 50
    repeat.wait: 20
    remap.space2shiftL_space_keyrepeat: 1
    option.emacsmode_controlM: 1
    remap.swapcolons: 1

osx_defaults:
  dock:
    -
      domain: com.apple.dock
      name: autohide
      type: bool
      value: true
    -
      domain: com.apple.dock
      name: autohide-delay
      type: float
      value: 0
    -
      domain: com.apple.dock
      name: showhidden
      type: bool
      value: true
    -
      domain: com.apple.dock
      name: mouse-over-hilite-stack
      type: bool
      value: true
    -
      domain: com.apple.dock
      name: expose-animation-duration
      type: float
      value: 0.1
    -
      domain: com.apple.dock
      name: persistent-apps
      type: array
      value:
  systemui:
    -
      domain: com.apple.menuextra.battery
      name: ShowPercent
      type: bool
      value: true
    -
      domain: -g
      name: AppleEnableMenuBarTransparency
      type: bool
      value: false
  others:
    -
      domain: -g
      name: AppleKeyboardUIMode
      type: int
      value: 3
    -
      domain: -g
      name: NSNavPanelExpandedStateForSaveMode
      type: bool
      value: true
    -
      domain: -g
      name: NSAutomaticSpellingCorrectionEnabled
      type: bool
      value: false
    -
      domain: -g
      name: NSAutomaticSubstitutionEnabled
      type: bool
      value: false
    -
      domain: -g
      name: NSAutomaticQuoteSubstitutionEnabled
      type: bool
      value: false
    -
      domain: -g
      name: NSAutomaticDashSubstitutionEnabled
      type: bool
      value: false
    -
      domain: -g
      name: com.apple.keyboard.fnState
      type: bool
      value: true
    -
      domain: com.apple.desktopservices
      name: DSDontWriteNetworkStores
      type: bool
      value: true
    -
      domain: com.apple.screensaver
      name: askForPassword
      type: bool
      value: true
    -
      domain: com.apple.screensaver
      name: askForPasswordDelay
      type: float
      value: 0
    -
      domain: com.apple.universalaccess
      name: mouseDriverCursorSize
      type: int
      value: 4

rbenv:
  versions:
    - 2.2.1

plenv:
  versions:
    - 5.20.2

aquaskk:
  synced_dictionaries:
    - /Users/aereal/Dropbox/skk/skk-jisyo.utf8

fonts:
  casks:
    - font-anonymous-pro
    - font-camingocode
    - font-fantasque-sans-mono
    - font-fira-sans
    - font-inconsolata-dz
    - font-meslo-lg
    - font-novamono
    - font-oxygen-mono
    - font-share-tech-mono
    - font-source-code-pro
    - font-ubuntu
