---

-
  name: Apply defaults
  defaults:
    domain: "{{ item.domain }}"
    name: "{{ item.name }}"
    type: "{{ item.type | default('string') }}"
    value: "{{ item.value }}"
  with_items: osx_defaults.others

-
  name: Apply Dock defaults
  defaults:
    domain: "{{ item.domain }}"
    name: "{{ item.name }}"
    type: "{{ item.type | default('string') }}"
    value: "{{ item.value }}"
  with_items: osx_defaults.dock
  notify: restart Dock

-
  name: Apply System UI Server defaults
  defaults:
    domain: "{{ item.domain }}"
    name: "{{ item.name }}"
    type: "{{ item.type | default('string') }}"
    value: "{{ item.value }}"
  with_items: osx_defaults.systemui
  notify: restart SystemUIServer
