---

-
  name: Install packages
  homebrew:
    name={{ item.name }}
    state={{ item.state | default('present') }}
    install_options="{{ item.install_options | default('') }}"
  with_items: homebrew_packages.packages
