ANSIBLE_PLAYBOOK_CMD = ansible-playbook
ANSIBLE_SITE_PLAYBOOK_FILE = site.yml
ANSIBLE_SETUP_PLAYBOOK_FILE = setup.yml

apply:
	$(ANSIBLE_PLAYBOOK_CMD) $(ANSIBLE_SITE_PLAYBOOK_FILE)

setup:
	$(ANSIBLE_PLAYBOOK_CMD) $(ANSIBLE_SETUP_PLAYBOOK_FILE)

test:
	$(ANSIBLE_PLAYBOOK_CMD) --syntax-check $(ANSIBLE_SITE_PLAYBOOK_FILE)
