---

-
  name: Tap caskroom/versions
  homebrew_tap:
    name: 'caskroom/versions'

-
  name: Install Cask
  homebrew_cask:
    state={{ item.state | default('present') }}
    name={{ item.name }}
  with_items: homebrew_cask.casks
